apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myfirstapi
  namespace: site
  labels:
    app: myfirstapi
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: myfirstapi
  template:
    metadata:
      labels:
        app: myfirstapi
    spec:
      containers:
      - name: myfirstapi
        image: emersonvix/myfirstapi:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8000